export const CONVERSATIONS_REQUEST = '@@conversations/CONVERSATIONS_REQUEST'
export const CONVERSATIONS_SUCCESS = '@@conversations/CONVERSATIONS_SUCCESS'
export const CONVERSATIONS_FAILURE = '@@conversations/CONVERSATIONS_FAILURE'