export const WORLDS_GET_REQUEST = '@@worlds/WORLDS_GET_REQUEST'
export const WORLDS_GET_SUCCESS = '@@worlds/WORLDS_GET_SUCCESS'
export const WORLDS_GET_FAILURE = '@@worlds/WORLDS_GET_FAILURE'

export const WORLDS_CREATE_REQUEST = '@@worlds/WORLDS_CREATE_REQUEST'
export const WORLDS_CREATE_SUCCESS = '@@worlds/WORLDS_CREATE_SUCCESS'
export const WORLDS_CREATE_FAILURE = '@@worlds/WORLDS_CREATE_FAILURE'