export const LOG_OUT = 'LOG_OUT'
export const USER_CLEAR_ERRORS = 'USER_CLEAR_ERRORS'

export const LOG_IN_REQUEST = '@@user/LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = '@@user/LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = '@@user/LOG_IN_FAILURE'

export const REGISTER_REQUEST = '@@user/REGISTER_REQUEST'
export const REGISTER_SUCCESS = '@@user/REGISTER_SUCCESS'
export const REGISTER_FAILURE = '@@user/REGISTER_FAILURE'

export const JOIN_WORLD_REQUEST = '@@user/JOIN_WORLD_REQUEST'
export const JOIN_WORLD_SUCCESS = '@@user/JOIN_WORLD_SUCCESS'
export const JOIN_WORLD_FAILURE = '@@user/JOIN_WORLD_FAILURE'

export const LEAVE_WORLD_REQUEST = '@@user/LEAVE_WORLD_REQUEST'
export const LEAVE_WORLD_SUCCESS = '@@user/LEAVE_WORLD_SUCCESS'
export const LEAVE_WORLD_FAILURE = '@@user/LEAVE_WORLD_FAILURE'