export const VILLAGE_GET_REQUEST = '@@village/VILLAGE_GET_REQUEST'
export const VILLAGE_GET_SUCCESS = '@@village/VILLAGE_GET_SUCCESS'
export const VILLAGE_GET_FAILURE = '@@village/VILLAGE_GET_FAILURE'

export const VILLAGE_PATCH_REQUEST = '@@village/VILLAGE_PATCH_REQUEST'
export const VILLAGE_PATCH_SUCCESS = '@@village/VILLAGE_PATCH_SUCCESS'
export const VILLAGE_PATCH_FAILURE = '@@village/VILLAGE_PATCH_FAILURE'